---
- hosts: oncast
  become: 'yes'
  remote_user: ec2-user
  become_user: root
  roles:
    - prebuild

- hosts: services
  become: 'yes'
  remote_user: ec2-user
  become_user: root
  roles:
    - services

- hosts: docker
  become: 'yes'
  remote_user: ec2-user
  become_user: root
  roles:
    - docker

- hosts: deployment
  become: 'yes'
  remote_user: ec2-user
  become_user: root
  roles:
    - deployment

  pre_tasks:  
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      tags: 
        always