---
- hosts: oncast
  become: 'yes'
  remote_user: ec2-user
  become_user: root

  pre_tasks:  
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      tags: 
        always
  tasks: 
    - name: Build Oncast
      include_role:
        name: prebuild
        name: services
        name: docker
        name: deployment