---
- hosts: oncast
  become: 'yes'
  remote_user: ec2-user
  become_user: root
  roles:
    - prebuild
    - services
    - docker
    - deployment

  pre_tasks:  
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      tags: 
        always