---
- name: Stop and Tar Image
  shell: docker commit -c "EXPOSE 80" cmx-container -o hugoboss192/hariapp:dockertag
  shell: docker stop cmx-container || true
  tags: 
    - xmp 

- name: Display multiple file content
  debug: var=item
  with_file:
    - /var/lib/jenkins/workspace/workspaces.txt
    - /var/lib/jenkins/workspace/xmc-checking.txt
  tags:
    - oncast

- name: Copy file
  ansible.builtin.copy:
    src: /var/lib/jenkins/workspace/workspaces.txt
    dest: /home/ec2-user/
  tags: 
    - oncast

- name: Compress file
  archive:
    path: /var/lib/jenkins/workspace/xmc-checking.txt
    dest: /var/lib/jenkins/workspace/xmc-checking.txt.tgz
  tags: 
    - oncast
        
- name: Move file
  ansible.builtin.command: mv /var/lib/jenkins/workspace/xmc-checking.txt.tgz /var/lib/jenkins/workspace/ONCAST/xmc-checking.txt.tgz
  tags: 
    - oncast